### ISSUE TITLE
Error connecting to Redis instance

### ISSUE THREAD

**Issue by SvenKratzEasel** [DavidBM/rsmq-async-rs#16]
Hi we're having trouble connecting to our Redis instance, and we believe we've set all `RsmqOptions` correctly (e.g., hostname and password work when connecting manually via redis-cli). There might be a bug in the way the password is prefixed with "redis" in `normal_facade.rs` (l24):

```
 pub async fn new(options: RsmqOptions) -> RsmqResult<Rsmq> {
        let password = if let Some(password) = options.password.clone() {
            format!("redis:{}@", password)
        } else {
            "".to_string()
        }; 
```

Is prefixing "redis" a necessity? I think this is causing our authentication issue.

**Comment by DavidBM** [comment]
Yeah, that is a bug. One sec and I will fix it

**Comment by DavidBM** [comment]
What is happening there is that the username is "redis" and then it is inserting the password into the string. 

Does the password contain characters like ":" or "@"?

**Comment by DavidBM** [comment]
I think I will change it so it uses the redis `ConnectionInfo` type directly rather than an string. So we can avoid problems with passwords with special characters

**Comment by DavidBM** [comment]
It would be similar if you use the normal facade, btw. 

I see the interface isn't ideal. I will see if I can code some better functions tonight or tomorrow. Meanwhile, try that and let me know

**Comment by DavidBM** [comment]
Just updated the library to v6.0.0 which uses the internal types from redis to build the `ConnectionInfo` so the password is passed as-is to the redis library. That should fix your issues.

**Comment by SvenKratzEasel** [comment]
Thanks, David, we'll try it out!
