### ISSUE TITLE
get_queue should handle < 1s's precision

### ISSUE THREAD

**Issue by GopherJ** [DavidBM/rsmq-async-rs#25]
```rs
        let result: (Vec<Option<String>>, (u64, u64)) = pipe()
            .atomic()
            .cmd("HMGET")
            .arg(format!("{}{}:Q", self.ns, qname))
            .arg("vt")
            .arg("delay")
            .arg("maxsize")
            .cmd("TIME")
            .query(conn)?;

        let time_millis = (result.1).0 * 1000;
```

now get_queue just use seconds as queue.ts and uses that as a score for incoming message, we lose some precision here

**Comment by GopherJ** [comment]
Ref: https://github.com/smrchy/rsmq/blob/5c507c2ae97145fbdef7369da52dc69b105e0cc6/index.js#L44

**Comment by GopherJ** [comment]
https://github.com/smrchy/rsmq/blob/5c507c2ae97145fbdef7369da52dc69b105e0cc6/index.js#L175 here it throw away the milli seconds, but I feel we should be consistent

**Comment by DavidBM** [comment]
Hi! I'm happy to add that to the library. 
Just two things:
- Can you make an MR?
- We should make it optional, as I want for it to still be compatible with the Nodejs version of it. So we can have a "js_compatible" feature that uses seconds, and have it disabled by default.

What do you think?

**Comment by GopherJ** [comment]
yes I'll make a PR

**Comment by GopherJ** [comment]
@DavidBM raised simple PR at: GopherJ:fix/score-precision

**Comment by DavidBM** [comment]
@GopherJ The MR is good! But could you make it so the changes are under a feature flag?

**Comment by DavidBM** [comment]
I merged your MR and followed up with some changes. Now your time precision is hidden behind a flag. You can enable it by adding rsmq async to your crate like this:
```toml
rsmq_async = { version = "11", features = [ "break-js-comp" ] }
```
